listen: 0.0.0.0:443
vhosts:
  - name: vmess.example.com
    tlsoffloading: true
    cert: ./example.com.pem
    key: ./example.com.key
    http:
      handler: fileServer
      args: /var/www/html
    default:
      handler: proxyPass
      args: 127.0.0.1:40001
  - name: trojan.example.com
    tlsOffloading: false
    default:
      handler: proxyPass
      args: 127.0.0.1:8443